site_name: Sistema De Alquiler De Vehiculos
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate # modo oscuro
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

pluggins:
  - search:
  - mkdocstrings:
    handlers:
      python:
        paths: ["src"]

nav:
  - Inicio: index.md
  - Referencias: api.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences