site_name: Sistema De Alquiler De Vehiculos

theme:
  name: material

nav:
  - Inicio: index.md
  - Base de Datos: database.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
